--[[ Lights Out -- switch every light off.

  Pressing a cell flips it and its four neighbours. Puzzles are generated by
  starting from a solved board and applying random presses, so every board is
  guaranteed solvable, and the number of presses used to scramble it is a
  genuine upper bound on the solution length.
]]

local req = ...
local gfx = req("lib.gfx")
local audio = req("lib.audio")

local floor = math.floor
local max, min = math.max, math.min

local N = 5
local CELL_W, CELL_H = 7, 2
local GAP = 1
local ORIGIN_X = floor((gfx.W - (N * (CELL_W + GAP) - GAP)) / 2) + 1
local ORIGIN_Y = 3

local Game = {}
Game.__index = Game

local BULB_ON = gfx.makeGlyph({
  "............",
  "..########..",
  ".##########.",
  ".##########.",
  "..########..",
  "............",
})
local BULB_OFF = gfx.makeGlyph({
  "..........",
  "...####...",
  "..######..",
  "..######..",
  "...####...",
  "..........",
})

------------------------------------------------------------------ instance
local function new(api, mode)
  local self = setmetatable({}, Game)
  self.api = api
  self.scramble = (mode and mode.scramble) or 4
  self.growth = (mode and mode.growth) or 1
  self.board = {}
  self.round = 0
  self.moves = 0
  self.totalMoves = 0
  self.score = 0
  self.finished = false
  self.won = false
  self.cursorX, self.cursorY = 3, 3
  self.time = 0
  self.parCleared = false
  self.limit = (mode and mode.limit) or 120
  self.flash = 0
  self:deal()
  return self
end

function Game:index(x, y) return (y - 1) * N + x end

function Game:press(x, y, silent)
  local function flip(cx, cy)
    if cx < 1 or cx > N or cy < 1 or cy > N then return end
    local i = self:index(cx, cy)
    self.board[i] = not self.board[i]
  end
  flip(x, y)
  flip(x - 1, y)
  flip(x + 1, y)
  flip(x, y - 1)
  flip(x, y + 1)
  if not silent then
    self.moves = self.moves + 1
    self.totalMoves = self.totalMoves + 1
    audio.play(self.board[self:index(x, y)] and "lo.on" or "lo.off")
  end
end

function Game:lit()
  local n = 0
  for i = 1, N * N do
    if self.board[i] then n = n + 1 end
  end
  return n
end

--- Build a fresh board that is solvable by construction.
function Game:deal()
  self.round = self.round + 1
  self.moves = 0
  self.par = self.scramble + (self.round - 1) * self.growth
  if self.par > 14 then self.par = 14 end
  for i = 1, N * N do self.board[i] = false end
  local guard = 0
  repeat
    guard = guard + 1
    for i = 1, N * N do self.board[i] = false end
    for _ = 1, self.par do
      self:press(math.random(1, N), math.random(1, N), true)
    end
  until self:lit() > 0 or guard > 20
  self.moves = 0
end

--------------------------------------------------------------------- input
function Game:activate()
  if self.finished then return end
  self:press(self.cursorX, self.cursorY)
  if self:lit() == 0 then
    -- efficiency bonus: solving in no more presses than the scramble took
    if self.moves <= self.par then self.parCleared = true end
    local bonus = max(0, self.par * 2 - self.moves) * 15
    self.score = self.score + 200 + self.round * 50 + bonus
    self.flash = 0.6
    audio.play("lo.solved")
    self:deal()
  end
end

function Game:onKey(code, held)
  if self.finished then return end
  if code == keys.left or code == keys.a then
    self.cursorX = max(1, self.cursorX - 1)
  elseif code == keys.right or code == keys.d then
    self.cursorX = min(N, self.cursorX + 1)
  elseif code == keys.up or code == keys.w then
    self.cursorY = max(1, self.cursorY - 1)
  elseif code == keys.down or code == keys.s then
    self.cursorY = min(N, self.cursorY + 1)
  elseif not held and (code == keys.space or code == keys.enter) then
    self:activate()
  end
end

function Game:onMouse(kind, btn, x, y)
  if kind ~= "mouse_click" or self.finished then return end
  local gx = floor((x - ORIGIN_X) / (CELL_W + GAP)) + 1
  local gy = floor((y - ORIGIN_Y) / (CELL_H + GAP)) + 1
  if gx < 1 or gx > N or gy < 1 or gy > N then return end
  self.cursorX, self.cursorY = gx, gy
  self:activate()
end

-------------------------------------------------------------------- update
function Game:update(dt)
  if self.finished then return end
  if self.flash > 0 then self.flash = self.flash - dt end
  self.time = self.time + dt
  if self.time >= self.limit then
    self.finished = true
    self.won = self.round > 3
    audio.play("result.lose")
  end
end

---------------------------------------------------------------------- draw
function Game:draw()
  gfx.clear(colors.black)

  local hudBg = self.flash > 0 and colors.green or colors.gray
  gfx.fill(1, 1, gfx.W, 1, hudBg)
  gfx.text(2, 1, "SCORE", colors.lightGray, hudBg)
  gfx.text(8, 1, gfx.commas(self.score), colors.white, hudBg)
  gfx.center(1, "BOARD " .. self.round, colors.yellow, hudBg)
  local left = max(0, floor(self.limit - self.time))
  gfx.right(gfx.W - 1, 1, left .. "s", left <= 15 and colors.red or colors.lightGray, hudBg)
  gfx.right(gfx.W - 8, 1, self.moves .. "/" .. self.par, colors.lightGray, hudBg)

  for y = 1, N do
    for x = 1, N do
      local sx = ORIGIN_X + (x - 1) * (CELL_W + GAP)
      local sy = ORIGIN_Y + (y - 1) * (CELL_H + GAP)
      local on = self.board[self:index(x, y)]
      local cursor = (x == self.cursorX and y == self.cursorY)
      local bg
      if on then
        bg = cursor and colors.white or colors.yellow
      else
        bg = cursor and colors.lightGray or colors.gray
      end
      gfx.fill(sx, sy, CELL_W, CELL_H, bg)
      gfx.blitGlyph(sx + 1, sy, on and BULB_ON or BULB_OFF,
        on and colors.orange or colors.black, bg)
    end
  end

  gfx.rule(1, 18, gfx.W, colors.gray, colors.black)
  gfx.center(19, "Arrows move   Space press   " .. self:lit() .. " lit",
    colors.lightGray, colors.black)
end

function Game:summary()
  return {
    { "Boards cleared", self.round - 1 },
    { "Presses", self.totalMoves },
  }
end

---------------------------------------------------------------------- cover
local function cover(c, t)
  c:clear(colors.black)
  local cell = 9
  local ox = floor((c.w - 5 * cell) / 2)
  local oy = floor((c.h - 3 * cell) / 2)
  local phase = floor(t * 2)
  for row = 1, 3 do
    for col = 1, 5 do
      local on = ((col * 3 + row * 5 + phase) % 4) < 2
      local x = ox + (col - 1) * cell
      local y = oy + (row - 1) * cell
      c:fill(x, y, cell - 2, cell - 2, on and colors.yellow or colors.gray)
      if on then
        c:fill(x + 2, y + 2, cell - 6, cell - 6, colors.orange)
      end
    end
  end
end

----------------------------------------------------------------- definition
return {
  id = "lightsout",
  name = "Lights Out",
  tagline = "Switch them all off",
  accent = colors.yellow,
  order = 110,
  cover = cover,
  music = "quiet",
  controls = {
    { "Arrows / WASD", "Move cursor" },
    { "Space", "Press a light" },
    { "Click", "Press a light" },
    { "", "Flips it and its neighbours" },
    { "P", "Pause menu" },
  },
  modes = {
    { id = "gentle", name = "Gentle", hint = "4 min, easy", scramble = 3, growth = 1, limit = 240 },
    { id = "standard", name = "Standard", hint = "2 min", scramble = 4, growth = 1, limit = 120 },
    { id = "tangled", name = "Tangled", hint = "3 min, messy", scramble = 7, growth = 1, limit = 180 },
  },
  trophies = {
    { id = "lo_5", name = "Sparks Out", desc = "Clear five boards in a run",
      test = function(g) return g.round - 1 >= 5 end },
    { id = "lo_perfect", name = "No Wasted Moves", desc = "Clear a board in par",
      test = function(g) return g.parCleared end },
    { id = "lo_10", name = "Blackout", desc = "Clear ten boards in a run",
      test = function(g) return g.round - 1 >= 10 end },
  },
  new = new,
}
